name: Test Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v2
      # Update svg widget in README
      - name: Update version in README
        id: change_version
        run: |
          TAG_VERSION=$(git describe --tags --abbrev=0)
          if [ -z "$TAG_VERSION" ]; then
            echo "No tags found."
            exit 1
          fi
          echo "Latest tag version: $TAG_VERSION"
          TAG_VERSION=${TAG_VERSION:12}
          echo "Latest tag version: $TAG_VERSION"
          sed 's/v[0-9].[0-9].[0-9]+[0-9]/'"$TAG_VERSION"'/g' ./folder/badge.svg > ./folder/badge.svg.tmp     
          mv ./folder/badge.svg.tmp ./folder/badge.svg
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ./folder/badge.svg
          git commit -m "Update Dev version in README"
          git push origin HEAD:refs/heads/main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



